export const levelLabels: Record<string, string> = {
  easy: "Easy",
  normal: "Normal",
  hard: "Hard",
  random: "Random",
  "guideline-easy": "Guideline Easy",
  "guideline-normal": "Guideline Normal",
  "guideline-hard": "Guideline Hard",
  "guideline-random": "Guideline Random",
  "practice-easy": "Practice Easy",
  "practice-normal": "Practice Normal",
  "practice-hard": "Practice Hard",
  "cloud-module-2": "Module 2",
  "cloud-module-3": "Module 3",
  "cloud-module-4": "Module 4",
  "cloud-module-5": "Module 5",
  "cloud-module-6": "Module 6",
  "cloud-module-7": "Module 7",
  "cloud-module-8": "Module 8",
  "cloud-module-10": "Module 10",
  "cloud-module-11": "Module 11",
  "cloud-module-12": "Module 12",
  "cloud-module-13": "Module 13",
  "cloud-module-14": "Module 14",
};

export const levelColors: Record<string, string> = {
  easy: "bg-green-500",
  normal: "bg-yellow-500",
  hard: "bg-red-500",
  random: "bg-purple-500",
  "guideline-easy": "bg-green-500",
  "guideline-normal": "bg-yellow-500",
  "guideline-hard": "bg-red-500",
  "guideline-random": "bg-purple-500",
  "practice-easy": "bg-green-500",
  "practice-normal": "bg-yellow-500",
  "practice-hard": "bg-red-500",
  "cloud-module-2": "bg-orange-500",
  "cloud-module-3": "bg-orange-500",
  "cloud-module-4": "bg-orange-500",
  "cloud-module-5": "bg-orange-500",
  "cloud-module-6": "bg-orange-500",
  "cloud-module-7": "bg-orange-500",
  "cloud-module-8": "bg-orange-500",
  "cloud-module-10": "bg-orange-500",
  "cloud-module-11": "bg-orange-500",
  "cloud-module-12": "bg-orange-500",
  "cloud-module-13": "bg-orange-500",
  "cloud-module-14": "bg-orange-500",
};
